/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VitepressAnimeTracker {
        "api": string;
        "bgmEnabled": boolean;
        "bgmUid"?: string;
        "bilibiliEnabled": boolean;
        "bilibiliUid"?: string;
        "customEnabled": boolean;
        "customLabel": string;
        "pageSize": number;
    }
}
declare global {
    interface HTMLVitepressAnimeTrackerElement extends Components.VitepressAnimeTracker, HTMLStencilElement {
    }
    var HTMLVitepressAnimeTrackerElement: {
        prototype: HTMLVitepressAnimeTrackerElement;
        new (): HTMLVitepressAnimeTrackerElement;
    };
    interface HTMLElementTagNameMap {
        "vitepress-anime-tracker": HTMLVitepressAnimeTrackerElement;
    }
}
declare namespace LocalJSX {
    interface VitepressAnimeTracker {
        "api"?: string;
        "bgmEnabled"?: boolean;
        "bgmUid"?: string;
        "bilibiliEnabled"?: boolean;
        "bilibiliUid"?: string;
        "customEnabled"?: boolean;
        "customLabel"?: string;
        "pageSize"?: number;
    }
    interface IntrinsicElements {
        "vitepress-anime-tracker": VitepressAnimeTracker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vitepress-anime-tracker": LocalJSX.VitepressAnimeTracker & JSXBase.HTMLAttributes<HTMLVitepressAnimeTrackerElement>;
        }
    }
}
